Blogs: Endpoint for a new BuddyPress blog
buddypress/BP-REST pull request #352
Opened 2020-09-14 03:48 UTC by renatonascalves

fixes #310

2020-09-16 19:44 UTC, imath requested changes
Hi @renatonascalves 

Thanks a lot for your work on this. I've suggested some improvements, the main one is to use `wpmu_validate_blog_signup()` to valide the blog `name` and `title` and get the blog `domain` and `path`.

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +		 * @since 6.0.0
It will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +	 * @since 6.0.0
it will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +		 * @since 6.0.0
t will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +	 * @since 6.0.0
t will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +		 * @since 6.0.0
t will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +	 * @since 6.0.0
t will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +		 * @since 6.0.0
t will be introduced in BP 7.0.0 => `@since 7.0.0`

2020-09-16 19:44 UTC, imath commented on tests/blogs/test-controller.php
>  	public function test_get_item_invalid_group_id() {
shouldn't this function be named `test_get_item_invalid_blog_id()`?

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +
There should be a validate check:

```php
$blog = wpmu_validate_blog_signup( $name, $title );
if ( is_wp_error( $blog['errors'] ) ) {
	return new WP_Error(
		'bp_rest_blog_validation_failed',
		$blog['errors']->get_error_message(),
		array(
			'status' => 500,
		)
	);
}
```

This check will give you an array containing the validated `domain`, `path`, `blogname` and `blog_title`.

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +		$path    = $request->get_param( 'path' );
Domain and path should be generated using `wpmu_validate_blog_signup()` see next comment, the blog `$name` should be one of the arguments.

```php
$name = $request->get_param( 'name' );
```

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +			$domain,
this should be: `$blog['domain'] // the validated domain`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +			$path,
this should be: `$blog['path'] // the validated path`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +			$title,
this should be: `$blog['blog_title'] // the validated title`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +			);
Remove this argument.

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +			$args['path'] = array(
rename this one for `$args['name']`

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +				'sanitize_callback' => 'sanitize_text_field',
It would probably better to use `array( $this, 'sanitize_slug' )` as the sanitize callback.

2020-09-16 19:44 UTC, imath commented on includes/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
> +				'description'       => __( 'The new site\'s path.', 'buddypress' ),
Suggestion: `__( 'The new site\'s name (used for the site URL).', 'buddypress' )`

2020-09-20 17:13 UTC, renatonascalves commented
@imath Updated with your suggestions! :)

2020-09-20 18:47 UTC, imath approved these changes
Looks great! Thanks a lot for your work on this 💪

2020-09-21 16:25 UTC, merged