Add sitewide notices endpoint.
buddypress/BP-REST pull request #411
Opened 2021-07-06 17:50 UTC by dcavins

Allow any logged-in user to fetch currently active notices that they haven't dismissed.
Allow any logged-in user to dismiss the currently active notice.
Allow site admins to create, fetch, and update sitewide notices.

2021-07-06 19:26 UTC, imath requested changes
Hi @dcavins 

Thank you so much for you work on this. We're running out of time for the 9.0.0-beta and I'm sorry I though the Notice endpoint was included into the BP REST API. This PR is very important to progress on https://github.com/buddypress/bp-blocks/issues/37 and finish the Widget migration (Sitewide notices).

Unit tests are failing because they need this PR to be merged first #410 I'm waiting for @renatonascalves 's review. But I believe, I'll commit it if I have no news from him tomorrow ;)

Could you have a look at my suggestions and fix these [WPCS issues](https://github.com/buddypress/BP-REST/runs/3001604658?check_suite_focus=true) ?

Don't hesitate to ping me if needed.

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$message = isset( $request['message'] ) ? $request['message'] : '';
```suggestion
		$subject = $request->get_param( 'subject' );
		$message = $request->get_param( 'message' );
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$notice = $this->get_notice_object( $request['id'] );
```suggestion
		$notice = $this->get_notice_object( $request->get_param( 'id' ) );
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$test_notice = $this->get_notice_object( $request['id'] );
```suggestion
		$test_notice = $this->get_notice_object( $request->get_param( 'id' ) );
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$notice   = $this->get_notice_object( $request['id'] );
```suggestion
		$notice   = $this->get_notice_object( $request->get_param( 'id' ) );
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @since 0.1.0
```suggestion
		 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 *
```suggestion
		 * @since 9.0.0
		 *
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	 * @since 0.1.0
```suggestion
	 * @since 9.0.0
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$notice_id       = isset( $request['id'] ) ? absint( $request['id'] ) : 0;
```suggestion
		$notice_id       = (int) $request->get_param( 'id' );
```

2021-07-06 19:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		}
I'd do like this:

```suggestion
		$subject = $request->get_param( 'subject' );
		if ( ! empty( $schema['properties']['subject'] ) && $subject ) {
			if ( is_string( $subject  ) ) {
				$prepared_item->subject = $subject;
			} elseif ( isset( $subject['raw'] ) ) {
				$prepared_item->subject = $subject['raw'];
			}
		}
```

Same for the `message` and `is_active` props

2021-07-06 19:30 UTC, imath commented
Update @renatonascalves just reviewed #410 Many thanks 😍 

I'd also like some unit tests if we have some time.

2021-07-06 20:00 UTC, renatonascalves requested changes
Added some suggestions! 

- You should try to get params using `$request->get_param(` as much as possible
- Confirm the notice ID exists before using it
- Schema caching
- Other minor things.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			array(
Add the id argument.
```

'args'   => array(
	'id' => array(
		'description' => __( 'A unique numeric ID for the message.', 'buddypress' ),
		'type'        => 'integer',
	),
),
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +				),
Should this be removed?

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +					'permission_callback' => array( $this, 'get_items_permissions_check' ), // Anyone who can get items can dismiss them.
I agree! This is a pattern we have been using in all endpoints.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +	public function get_endpoint_args_for_item_schema( $method = WP_REST_Server::CREATABLE ) {
Suggestion: I'd move this method to the bottom since we are doing the same in other endpoints.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +				$args['id'] = array(
I'd recommend having a global version and allow changing the description here.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$context  = ! empty( $request['context'] ) ? $request['context'] : 'view';
```suggestion
		$context  = $request->get_param( 'context' );
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		 * @param WP_REST_Request    $request  The request sent to the API.
```suggestion
		 * @param array                            $notices     Fetched notices.
		 * @param WP_REST_Response $response  The response data.
		 * @param WP_REST_Request    $request    The request sent to the API.
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$context = ! empty( $request['context'] ) ? $request['context'] : 'view';
```suggestion
		$context = $request->get_param( 'context' );
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		);
I wonder if we should really return an `array` with an object here. This was a mistake of mine in the beginning and I'd prefer we move away from that in single endpoints.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$test_notice = $this->get_notice_object( $request['id'] );
Could we also rename this variable?

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$notice->save();
If it fails, it should return an error here.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_moderate' ) || ! $notice->delete() ) {
There are two different errors here. One related to permissions, `! bp_current_user_can( 'bp_moderate' )` and another related to database entry. Both are returning the same error message.

I'd recommend separating them.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$retval = bp_current_user_can( 'bp_moderate' );
If this fails, it should not only return `false`, it should a permission error. Something like:

```
$retval = new WP_Error(
	'bp_rest_authorization_required',
	__( 'Sorry, you are not allowed to perform this action.', 'buddypress' ),
	array(
		'status' => rest_authorization_required_code(),
	)
);
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$context  = ! empty( $request['context'] ) ? $request['context'] : 'view';
```suggestion
		$context  = $request->get_param( 'context' );
```

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		return new BP_Messages_Notice( $id );
This might be return an object with a `null` id. Or it might return an object with whatever ID you pass along, regardless if it exists or not. So there should happen some sort of confirmation the notice actually exist in the database here.

2021-07-06 20:00 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$schema = array(
Missing schema caching here.

2021-07-06 20:31 UTC, dcavins commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +					'permission_callback' => array( $this, 'get_items_permissions_check' ), // Anyone who can get items can dismiss them.
Ha, well I guessed right on that for the create, update and delete methods then. Pure luck!

2021-07-06 20:36 UTC, dcavins commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			$args['subject']['type']        = 'string';
Sure, that is the response format. So it should be:
`$args['subject']['type']        = 'object';`
?

2021-07-06 21:06 UTC, dcavins commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_moderate' ) || ! $notice->delete() ) {
Do I need that `bp_current_user_can( 'bp_moderate' )` check in the method if it's in the `delete_item_permissions_check()` method? I felt like I was repeating myself.

2021-07-06 21:08 UTC, dcavins commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$schema = array(
Sorry, I'm not sure what you mean. Can you link to an example?

2021-07-06 21:10 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$schema = array(
@dcavins https://github.com/buddypress/BP-REST/blob/6948c93b15db8ff46a81dfd37266b5e80d1663e1/includes/bp-messages/classes/class-bp-rest-messages-endpoint.php#L1101

2021-07-06 21:11 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_moderate' ) || ! $notice->delete() ) {
You are correct! You do not need that. :)

2021-07-07 06:25 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			$args['subject']['type']        = 'string';
OOps, my bad. You're actually doing it the right way into the schema description. I understand now looking at the `create_item()` why you are overriding the schema here. No changes are needed here.

2021-07-07 06:26 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			$args['message']['type']        = 'string';
OOps, my bad. You're actually doing it the right way into the schema description. I understand now looking at the `create_item()` why you are overriding the schema here. No changes are needed here.

2021-07-08 04:16 UTC, imath requested changes
The PR still needs unit tests. I'll work on these asap.

2021-07-09 04:45 UTC, imath commented
@dcavins I've initialized unit tests, don't forget to `git pull` before editing you PR 😉, don't hesitate to carry on building some other tests, I'm going to move for a while on improving Dynamic Groups/Friends Widget Blocks.

2021-07-09 15:10 UTC, renatonascalves requested changes
Some comments.

2021-07-09 15:10 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +		$this->old_current_user = get_current_user_id();
I've removed this in other unit tests and saw no difference whatsoever. I wonder what this is actually doing since it doesn't seem to be breaking anything.

2021-07-09 15:10 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +		$request->set_param( 'context', 'edit' );
`edit`?

2021-07-09 15:10 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +	public function test_get_item() {
I'd add a test if the ID doesn't exit.

2021-07-09 17:21 UTC, imath commented on tests/sitewide-notices/test-controller.php
> +		$request->set_param( 'context', 'edit' );
Yes if `edit` is the context then it's the admin managing notices, so it fetches all notices. If `view` is the context only the active notice is fetched to the admin or any user.

2021-07-09 17:22 UTC, imath commented on tests/sitewide-notices/test-controller.php
> +		$this->old_current_user = get_current_user_id();
I'll look at it, but I believe it's too make sure to reset to the user that was set before we change it into the test.

2021-07-09 17:26 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +		$this->old_current_user = get_current_user_id();
Interesting! I'm not sure if that's doing that.

2021-07-10 18:37 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		return new BP_Messages_Notice( $id );
I confirm it returns a notice with the ID you pass but all other properties are an empty string.

2021-07-10 20:38 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		return new BP_Messages_Notice( $id );
That's right, if you see how this is being verified in the endpoint

This can add a false positive where the ID is there but the notice doesn't exist in the site.
```
if ( ! $notice->id ) {
    return $error;
}

```

2021-07-11 02:31 UTC, imath approved these changes

2021-07-11 15:30 UTC, renatonascalves approved these changes
I added a few suggestions but I think the code looks good. :)

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			$dismiss_endpoint,
Any reason to not do this?
```suggestion
		register_rest_route(
			$this->namespace,
			'/' . $this->rest_base . '/dismiss',
```

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$context = ! empty( $request['context'] ) ? $request['context'] : 'view';
In the `get_items_permissions_check`, you expect the context to be there, but here I see this conditional.

```suggestion
		$context = $request->get_param( 'context' );
```

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +
```suggestion
```

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +						);
Why not use the same error set in the beginning of this method? They are almost the same.
```suggestion
						$retval = $retval;
```

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +
```suggestion
```

2021-07-11 15:30 UTC, renatonascalves commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +
```suggestion
```

2021-07-11 15:30 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +	public function test_get_item_not_exist() {
```suggestion
	public function test_get_item_with_invalid_id() {
```

2021-07-11 15:30 UTC, renatonascalves commented on tests/sitewide-notices/test-controller.php
> +		$request = new WP_REST_Request( 'GET', $this->endpoint_url . '/' . $id );
You could also test passing `REST_TESTS_IMPOSSIBLY_HIGH_NUMBER`.

2021-07-11 16:20 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +			$dismiss_endpoint,
I don't think so, I agree & I've applied your suggestion 👍

2021-07-11 16:20 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +		$context = ! empty( $request['context'] ) ? $request['context'] : 'view';
Good catch! Thanks a lot. I've updated the PR accordingly

2021-07-11 16:21 UTC, imath commented on includes/bp-messages/classes/class-bp-rest-sitewide-notices-endpoint.php
> +						);
I agree! Thanks for your suggestion.

2021-07-11 16:22 UTC, imath commented on tests/sitewide-notices/test-controller.php
> +	public function test_get_item_not_exist() {
I've edited this and `update_item`, `delete_item` tests.

2021-07-11 16:22 UTC, imath commented on tests/sitewide-notices/test-controller.php
> +		$request = new WP_REST_Request( 'GET', $this->endpoint_url . '/' . $id );
Let's save some lines of code, I agree!

2021-07-11 16:28 UTC, merged