Update get_items xprofile parameter type
buddypress/BP-REST pull request #426
Opened 2021-10-18 06:08 UTC by adiloztaser

#425

2021-10-18 06:44 UTC, adiloztaser commented
The test passed which is I've written for for this PR but I think failed test is not relevant with this PR.

2021-10-21 20:24 UTC, imath commented
You're welcome @adiloztaser, I might get some red now. In JavaScript you can't build associative arrays but objects, so to be usable we need to also allow the `xprofile` collection argument to be an object.  We also need to differentiate where to find the relation type and the list of queries. Here's the test I performed to check it's working:

```javascript
bp.apiRequest( {
	path: 'buddypress/v1/members',
	type: 'GET',
	data: {
		context: 'view',
		'xprofile': {
			relation: 'AND',
			args: [
				{
					field: 'Test field',
					value: 'Hello world',
					compare: '='
				}
			]
		},
	}
} ).done( function( data ) {
	data.forEach( function( member ) {
		console.log( member.name + ' => ' + member.id );
	} );
} ).fail( function( error ) {
	return error;
} );
```

Unfortunately xProfile queries do not seem to support fields with multiple values (the ones that generate checkboxes, multiselect ...).

2021-10-21 21:24 UTC, adiloztaser commented
Thank you for the improvement @imath, really good catch.

I've updated the test function after your changes because it wasn't using the `xprofile` parameter into the query. I think new test request more accurate and reliable.

2021-11-02 02:50 UTC, renatonascalves requested changes
Looks good. I asked for two small changes before merging it.

2021-11-02 02:50 UTC, renatonascalves commented on tests/members/test-controller.php
> +		$this->assertSame( array( $u ), wp_list_pluck( $all_data, 'id' ) );
It would be good to test the second user is not in this array.

2021-11-02 02:50 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +						'relation' => $args['xprofile_query']['relation'],
Could you add a unit test using this relation?

2021-11-02 18:41 UTC, adiloztaser commented on tests/members/test-controller.php
> +		$this->assertSame( array( $u ), wp_list_pluck( $all_data, 'id' ) );
Thanks for advice. I've updated the test case for check this.

2021-11-02 18:43 UTC, adiloztaser commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +						'relation' => $args['xprofile_query']['relation'],
Good point, thanks for mentioning this. I've added new test cases both for `and` and `or` relations.

2021-11-03 03:15 UTC, renatonascalves approved these changes
Nice! This is good to go!

2021-11-03 03:15 UTC, merged