Add action links to items
buddypress/BP-REST pull request #447
Opened 2022-07-20 00:32 UTC by renatonascalves

fixes #444

2022-07-20 00:38 UTC, renatonascalves commented
@imath Could you take a look at the actions and confirm if I'm missing any?

2022-07-20 07:23 UTC, imath requested changes
Thanks for your work on this. I believe we should build these action links in a more dynamic way: only include the available actions according to the existing relationship between the logged in user and the object.

2022-07-20 07:23 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
>  		);
When we list groups into the Component's directory, and if the [user is not banned from the group](https://github.com/buddypress/buddypress/blob/master/src/bp-groups/bp-groups-template.php#L3583), we include a button to:
- request a membership for a private group (if not already a member of it)
- join a public group (if not already a member of it)
- leave a group (if already a member of it)
- accept an invitation to join a private group

See https://github.com/buddypress/buddypress/blob/master/src/bp-groups/bp-groups-template.php#L3574

I believe we should include action links dynamically according to the existing relation with the group.
- The logged in user is invited to join the group, there should be 2 action links: **accept** and **reject** invite.
- The logged in user is not a member of a public group, there should be 1 action link: **join**.
- The logged in user is a member of a group, there should be 1 action link: **leave**.
- The logged in user is not a member of a private group, there should be 1 action link: **request a membership**.
- The logged in user requested a membership to a private group, there should be 1 action link: **withdraw the request**.

2022-07-20 07:23 UTC, imath commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +			}
Here again these action links should be more dynamic according to the friendship relation of the logged in user with the listed user. See https://github.com/buddypress/buddypress/blob/master/src/bp-friends/bp-friends-template.php#L373

I believe we should use the existing `friendship_status_slug` schema property to decide what action links should be included, eg:
- `not_friend` -> an action link to init a friendship (add friend)
- `is_friend` -> an action link to delete the friendship
- `pending` -> an action link to cancel the friendship request
- `awaiting_response` -> 2 action links: one to accept & another one to reject the friendship request.

2022-07-20 07:23 UTC, imath commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +			if ( bp_is_active( 'messages' ) ) {
Private message are restricted to friends by default unless `buddypress()->messages->autocomplete_all` is `true`

2022-07-25 02:14 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
>  		);
Added as suggested!

2022-07-25 02:14 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +			}
Added as suggested!

2022-07-25 02:15 UTC, renatonascalves commented
@imath Could you take another look? :)

2022-07-25 12:34 UTC, imath submitted a review, later dismissed
Thanks a lot for your improvements. It's fine for friendship, there are just tiny fixes to bring and it should be good to be merged?

2022-07-25 12:34 UTC, imath commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +			}
Looks great, thanks you 👍

2022-07-25 12:34 UTC, imath commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +				&& buddypress()->messages->autocomplete_all === false
I believe it should be `&& ( true === wp_validate_boolean( $user_data['friendship_status'] ) || buddypress()->messages->autocomplete_all === true )`

It's possible to send PM when members are friends or autocomplete all is true.

2022-07-25 12:34 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +			$is_group_member      = $group->is_member;
`$group->is_member` is an int, we need to cast it as boolean: `(bool) $group->is_member;`

2022-07-25 12:35 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
>  		);
Thanks 👍

2022-07-25 12:41 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +			$is_group_member      = $group->is_member;
Oh and I forgot, I was a bit surprised by the `switch( true )` thing. Could we use an `if {} elseif {}...` instead ?

2022-07-26 13:42 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +				&& buddypress()->messages->autocomplete_all === false
Good catch! I misunderstood theh autocomplete part.

2022-07-26 13:48 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +			$is_group_member      = $group->is_member;
It's also a good approach to avoid complex if/else statements. Like the scenario here.

2022-07-26 14:28 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +			$is_group_member      = $group->is_member;
ok, fine about keeping the `switch( true )` approach. I'll try to get used to it :)

2022-07-27 00:15 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +			$is_group_member      = $group->is_member;
By the way, this is actually why I assumed it was a `bool`: https://github.com/buddypress/buddypress/blob/5cfd97515673dacc477902292547e268f19d1fa3/src/bp-groups/classes/class-bp-groups-group.php#L126

2022-07-27 21:29 UTC, imath approved these changes
Ready to go! Thanks again 👏

2022-07-27 23:37 UTC, merged