Support the bp_view capability.
buddypress/BP-REST pull request #487
Opened 2023-07-25 20:36 UTC by dcavins

This new capability will work with the community visibility features coming in BuddyPress 12.

Trac ticket: https://buddypress.trac.wordpress.org/ticket/8734

2023-07-26 05:37 UTC, imath commented
Hi @dcavins 

Thanks a lot for your patch, I saw only Members/Groups and xProfile endpoints were updated, shouldn't we do the same for the other component endpoints (except perhaps the signup one)?

2023-07-26 13:25 UTC, dcavins commented
Hi @imath,

Yes, I did not add `bp_view` checks in permission checks that were already more strict (like they already required that the user be logged in or have the bp_moderate capability). For instance:
https://github.com/buddypress/BP-REST/blob/master/includes/bp-friends/classes/class-bp-rest-friends-endpoint.php#L174

However, I can imagine adding the check so that plugins, etc, have a way to filter access to those items, even though in core, they probably won't be adding a stricter check, just potentially duplicating a check. What do you think?

2023-07-26 14:26 UTC, imath commented
Ah right 😅. I believe there are already filters in place into endpoints, so it's probably not an emergency for now, ideally it would probably be best to improve the way we check caps: but it can wait a bit longer. Thanks for your feedback.

2023-07-28 03:54 UTC, renatonascalves requested changes
Left a few considerations!

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
Regardless if you have this cap or not, we should check if the group ID exists **first**. Then we check for the user's permissions to view the group. 

Imagine a mobile app handling this response: should the app show a 404 page/screen or redirect the user to the login screen?

The error here might pass the wrong status of the _document_.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
The same suggestion I left for the group avatar.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
I'm also not sure this is the right error for this feature.

This function returns 401 if the user is not logged in, 403 if the user is logged in. I could be logged in and based on this feature flag, get a 401. A incorrect error code.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
We might need to investigate the recommended error code for this situation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
> +				);
The same suggestion. I think this should be checked first.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +	 * @return boolean
So, I actually think this change is incorrect. I could filter this hook and return an `WP_Error` object. The phpDoc is not only about what is used in the method but what it expects to be returned.

An intelephense tool, for example, will wrongly communicate this expects only a `boolean` when we know it doesn't.

Besides, `false` is the incorrect response for an error in a REST response. See the other examples where we are using a `WP_Error` object, not a `false` `boolean`.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +	 * @return boolean
It's either `true` or `WP_Error`.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +				);
The same suggestion. I think this should be checked first.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
Looks like you are duplicating this check here and on line 273.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
> +			);
The same suggestion. I think this should be checked first.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
> +			);
The same suggestion. I think this should be checked first.

2023-07-28 03:54 UTC, renatonascalves commented on includes/bp-members/classes/class-bp-rest-members-endpoint.php
> +	 * @return boolean
See my previous comment, the `boolean` `true` here without the `WP_Error` might've been an oversight on my part.

2023-07-28 13:53 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
This is a good question. I ordered the checks in this way because I thought if you didn't have the capability to access groups, then you shouldn't know whether group ID `x` resolved to a real group (to prevent fishing). I think this logic is similar to our hidden group logic. I am happy to be talked out of it, though, if that is the wrong way to approach a REST interaction. Thanks for reviewing this PR!

2023-07-28 13:57 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
I agree that this seems duplicative, but couldn't imagine leaving the `bp_view` check out of a function called `can_see()`. :) Happy to remove this if you prefer.

2023-07-28 14:02 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-groups-endpoint.php
> +	 * @return boolean
Thanks for the explanation! I'll change this back everywhere I made that error.

2023-07-29 15:07 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
Yes, the `bp_view` capability is invoked in the `pre_query` filter, before we know if the request would really resolve. https://github.com/buddypress/buddypress/blob/master/src/bp-core/classes/class-bp-component.php#L1265
@imath Do you agree with this statement?
Thanks again!

2023-07-29 15:12 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
In that case, I'd suggest following BP core and leaving as is. Maybe returning the proper error code so that consumers of this API can handle it properly in their apps.

2023-07-30 02:55 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
@dcavins @renatonascalves It happens just after we have set the BP Queried object, firstly to avoid WordPress to query for posts for nothing as we are in a BuddyPress area. The `BP_Component::pre_query()` method filters `posts_pre_query`. This means if a group or a user wasn't found, we'd get a 404 before reaching the login form. I think @dcavins logic: no access, no need to check further would be better, but as we need to make sure we're in a BuddyPress context it's a bit different than group access (where we know we're already in BuddyPress).

If we would show the login form instead of the 404, as we redirect to the requested page after login, we'd redirect to a 404 which is a bit annoying.

On the other hand, this is something we'll need to discuss about again: because in terms of "security" it could be annoying if I wanted to build a _super_ private community as showing a 404 before the login form means "I confirm something exists if you see this form...".

2023-07-30 15:55 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
I agree that no matter which order we do the checks in, someone will be unhappy with that decision. :) But I think that we should choose security/privacy over convenience, generally.

2023-07-30 16:18 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
This is an interesting question. I agree that I've been thinking too narrowly that if you don't have the `bp_view` capability you need to log in, but that only applies to the basic private site logic. 

The function `rest_authorization_required_code(`) does try to manage this situation, though, by sending the right code, depending on the user context: 401 if the user is not logged in, 403 if the user is logged in. https://developer.wordpress.org/reference/functions/rest_authorization_required_code/

Did WP save us a decision here?

2023-07-30 16:25 UTC, imath commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
I agree, 12.0.0-beta1 is tomorrow, this is something we can probably work on during the next 3 months. My first idea would be to include a new argument to `bp_do_404()` like $component, check cap inside it to eventually redirect to the component's directory.

2023-07-31 13:18 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +		if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
Sounds good. And I agree with the approach taken.

I do agree that some people might complain whatever approach is taken since I might be logged in already and if I deactivate access in one component, it'll redirect to the login page, even when I'm logged in. That'd be a weird user experience. I presume you'll provide ways to handle that in a non-REST context.

Here, the consumer of the API will have to handle these scenarios. :)

> I think that we should choose security/privacy over convenience, generally.

But it is odd that you see this as a security _thing_. If I visit `site.com/renato` and the page 404s, what's the security implication in this page not being found? Why that would be any different for a BuddyPress document?!

Even user IDs are exposed in the, WordPress, REST API. So as far as I know, there is no security or privacy implications here.

2023-07-31 13:24 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
If I understood this feature correctly, I can disable access to specific components, make them private. So it is technically possible to be logged in, having access to the app, and try to access an endpoint that's disabled. So the response would communicate the wrong response/code.

2023-07-31 13:56 UTC, imath commented
rest_authorization_required_code() is what WordPress uses when a user is not allowed to view a post. If it's not the right code, could you tell us what is the code to use ?

imath
https://imathi.eu
________________________________
De : Renato Alves ***@***.***>
Envoyé : Monday, July 31, 2023 3:29:37 PM
À : buddypress/BP-REST ***@***.***>
Cc : imath ***@***.***>; Mention ***@***.***>
Objet : Re: [buddypress/BP-REST] Support the bp_view capability. (PR #487)


@renatonascalves commented on this pull request.

________________________________

In includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php<https://github.com/buddypress/BP-REST/pull/487#discussion_r1279298730>:

> @@ -169,17 +169,27 @@ public function get_item( $request ) {
         * @return true|WP_Error
         */
        public function get_item_permissions_check( $request ) {
-               $retval      = new WP_Error(
-                       'bp_rest_group_invalid_id',
-                       __( 'Invalid group ID.', 'buddypress' ),
-                       array(
-                               'status' => 404,
-                       )
-               );
-               $this->group = $this->groups_endpoint->get_group_object( $request );
+               if ( ! bp_current_user_can( 'bp_view', array( 'bp_component' => 'groups' ) ) ) {
+                       $retval = new WP_Error(
+                               'bp_rest_authorization_required',
+                               __( 'Sorry, you cannot view group details.', 'buddypress' ),
+                               array(
+                                       'status' => rest_authorization_required_code(),


Just to confirm: in a REST context, that function is returning the wrong error code based on the status of the app. The consumer of the API will handle that but we are communicating the wrong code for this feature.

We can use that as well if we want but I'm just highlighting it so that we all understand it is not the correct code for the feature.

—
Reply to this email directly, view it on GitHub<https://github.com/buddypress/BP-REST/pull/487#discussion_r1279298730>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAN74HABFXRWIVEYJBYLULLXS6XMDANCNFSM6AAAAAA2XTLDAA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-31 14:18 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
Hi @renatonascalves, Thanks for your feedback! I'm sorry, I'm not understanding you. Here are some scenarios and the response codes that are received. Can you check that these make sense?

When the community visibility is set to "anyone" and I make an unauthenticated GET request to http://bpdevel.local/wp-json/buddypress/v1/members/1, I get a 200 response with the member info in the body.

When visibility is set to "members" and I resend the request (unauthenticated), I get 401 Unauthorized back.

If the user is logged in, I get a 200.

We're not limiting by component yet, but the framework to do so is in place, so if I add some custom code to prevent access to the members component for this user, using a filter like this:

```
add_filter( 'bp_map_meta_caps', 'prevent_non_admin_user_from_viewing_members_component', 15, 4 );
function prevent_non_admin_user_from_viewing_members_component( $caps, $cap, $user_id, $args ) {
	if ( 'bp_view' === $cap ) {
		$component = isset( $args[0]['bp_component'] ) ? $args[0]['bp_component'] : '';
		// Only 'admin' can view the memebers component.
		if ( 'members' === $component && 1 !== $user_id ) {
			$caps = array( 'do_not_allow' );
		}
	}
	return $caps;
}
```

then my logged-in user who can't view this item gets a 403 Forbidden response.

2023-07-31 14:22 UTC, imath commented on includes/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
Shouldn't we return a `rest_authorization_required_code()` WP Error instead ?

2023-07-31 14:22 UTC, imath commented on includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
Shouldn't we return a `rest_authorization_required_code()` WP Error instead ?

2023-07-31 14:22 UTC, imath commented on includes/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
Shouldn't we return a `rest_authorization_required_code()` WP Error instead ?

2023-07-31 14:23 UTC, dcavins commented
@imath You are correct about this:

> If you're logged in you have access to the endpoint, only not logged in users don't have access.
> The feature is: all that was publicly viewable by anyone becomes only viewable by logged in members.

but @renatonascalves makes an excellent point that visibility will be used in ways we do not expect. One example I can think of is for a subscription-based community site where, when your subscription expires, you can't view the community anymore (you no longer have the `bp_view` capability), whether you are logged in or not. So it's good to be thinking about this feature from different angles.

2023-07-31 14:32 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
Ah, are you talking about the `code` in this response and not the HTTP status code?

```
{
    "code": "bp_rest_authorization_required",
    "message": "Sorry, you are not allowed to perform this action.",
    "data": {
        "status": 403
    }
}
```

2023-07-31 14:36 UTC, dcavins commented
I think I finally understand that maybe Renato isn't talking about the HTTP status error code, but the code description, like `"code": "bp_rest_authorization_required",` and if that is the case, I can fix it! :)

2023-07-31 14:48 UTC, dcavins commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
For instance, we could do something like this?
```
		$retval = new WP_Error(
			( is_user_logged_in() ) ? 'rest_forbidden' : 'bp_rest_authorization_required',
			__( 'Sorry, you are not allowed to perform this action.', 'buddypress' ),
			array(
				'status' => rest_authorization_required_code(),
			)
		);
```
Or should the error description/id/code be more specific, like `bp_forbidden_cannot_view_{$component}`?

It looks like if this is the correct way to handle mixed permissions, we have a number of places to update this, for instance https://github.com/buddypress/BP-REST/blob/master/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L328

Thanks!

2023-07-31 14:55 UTC, renatonascalves commented
Maybe we should bring this conversation to Slack?

@dcavins The code I'm referring into is the HTTP code: 401 versus 403. This private feature is a flag feature and I was trying to call attention that those two error codes are not the true representation of this feature. If the site, or parts of it, is private, does it mean the user is logged out? That code, `bp_rest_authorization_required`, could be improved as well.

Some of my comments comes from some of the notes from the [ticket](https://buddypress.trac.wordpress.org/ticket/8734) and this screenshot: https://buddypress.trac.wordpress.org/attachment/ticket/8734/community-visibility-settings.png

I'm not sure if BP will start with a simple feature and expand it later. But based on what I read, it'd be technically possible to have access to the Activity component and be blocked from the Groups component.

From a REST context, in a app, the user is logged in. Requests are sent using tokens or cookies, for example, So we need a better way to communicate to the app that the component (the endpoint in this case) is blocked, not that the user is logged out, but that this is a feature flag which is blocking the request and the current user does not have access to it.

@imath In reply to your point [here](https://github.com/buddypress/BP-REST/pull/487#issuecomment-1658426066). ^ That's the reason that function does not communicate the true value. WordPress is using that function because it checks the user permissions, not if a feature flag is active.

That doesn't mean we can't use it for this purpose. I'm actually not even sure another HTTP error code exists for feature flags. Something to look into.

2023-07-31 14:57 UTC, renatonascalves commented on includes/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
> +					'status' => rest_authorization_required_code(),
I replied it here: https://github.com/buddypress/BP-REST/pull/487#issuecomment-1658538394

2023-08-01 17:58 UTC, imath commented
Hi @renatonascalves & @dcavins 

Is there any requested change that wasn't implemented yet? Or are we good to merge this PR ?

I see the review requested change is still in red.

2023-08-01 18:05 UTC, renatonascalves approved these changes

2023-08-01 18:05 UTC, renatonascalves commented
sorry, all good to me.

2023-08-01 18:07 UTC, imath commented
Thanks a lot @renatonascalves 👍. I'm merging the changes. Many thanks to @dcavins for the great work.

2023-08-01 18:10 UTC, merged